### ISSUE TITLE
That's some awesome city name.

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/provo#1]
I wonder if every citizen knows how to wield a katana...

**Comment by eafelix** [comment]
or use smoke bombs :P

**Comment by olizilla** [comment]
Would you consider sperating the concerns? 

Nodeschool is awesome;  ninjas are also awesome, but I think they both benefit from dedicated, independent, tireless study. 

The occasional _nodeschool and the ninjas_ christmas special with live-coding katas, shuiken-craft workshops and modular martial arts classes might do wonders for raising public awareness, but I think you'll get a more diverse (perhaps even occasionally ninja ambivalent, but that's ok too) group for the nodeschools.

**Comment by ghost** [comment]
Sorry for the late response, I inherited this group in February and overlooked this open issue.  

I changed the name for this repo to provo a couple months back.  I also created another chapter in Salt Lake City(slc).  For the purposes of management, we have a single entity, Utah Node.js Ninjas, managing both locations.  At each location, we have one day a month dedicated to nodeschool and one day a month for presentations.  

Do you think creating separate meetup pages for nodeschool would be beneficial?  I'm not looking forward to maintaining four meetup pages, but if you think it is best, I will consider it

Here is what we currently have:

http://www.meetup.com/Utah-Node-Ninjas/
http://www.meetup.com/utahnodejs/

We just recently acquired a sponsor for SLC which is why we don't have NodeSchools scheduled yet.  As soon as their facility completed, we'll have a nodeschool meetup once a month.

**Comment by a0viedo** [comment]
@majgis awesome work! keep with the good stuff
